djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import path, include

from userextend.forms import AuthenticationNewForm, NewPasswordChangeForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('trainer.urls')),
    path('', include('feedback.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path("password_change/", views.PasswordChangeView.as_view(form_class=NewPasswordChangeForm), name="password_change"),

    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# aceasta linie de cod face parte din config. fisierelor statice si utilizat pentru a asigura afisarea corecta
# a fisierului din MEDIA

# functia static primeste 2 args:
# settings.MEDIA_URL -> reprezinta url de baza pentru fisierele media
# document_root=settings.MEDIA_ROOT- reprezinta folderul fizic in care fisierele media sunt stocate


# in concluzie, serverul va putea prelua fisierele media prin intermediul url specificat

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home_page')
]

student/models.py
from django.contrib.auth.models import User
from django.db import models

from trainer.models import Trainer


# Create your models here.

class Student(models.Model):

    gender_options = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    first_name = models.CharField(max_length=31)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(null=True, blank=True)
    email = models.EmailField(max_length=50)
    description = models.TextField(max_length=300)
    start_date = models.DateField()
    end_date = models.DateField()
    active = models.BooleanField(default=True)
    gender = models.CharField(choices=gender_options, max_length=6)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)
    profile = models.ImageField(upload_to='profiles/', null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    #auto_now_add=True stocheaza data si ora cand a fost adaugata inregistrarea in tabela. Nu se mai modifica data si ora
    #auto_now = True stocheaza data si ora cand se realizeaza modificari pe respectiva inregistrare.

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


    #cele 2 comenzi IMPORTANTE pt a se salva fiecare modificare
    #python manage.py makemigrations
    #python manage.py migrate


class HistoryStudent(models.Model):
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.message

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
</head>
<body>
{% include 'navbar.html' %}
{% block content %} {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">IT platform</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'home_page' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Intro
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item"
                                   href="{% url 'list-cars' %}">List of cars</a>
                            </li>
                            <li><a class="dropdown-item"
                                   href="{% url 'list-movies' %}">List of
                                movies</a>
                            </li>

                        </ul>
                    </li>

                {% if  perms.student.add_student or perms.student.view_list_of_students%}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Students
                        </a>
                        <ul class="dropdown-menu">
                            {#                        {% if perms.app_label.codename %} {% endif %}#}
                            {% if perms.student.add_student %}
                                <li><a class="dropdown-item"
                                       href="{% url 'create-student' %}">Create
                                    a new
                                    student</a></li>
                            {% endif %}
                            {% if perms.student.view_list_of_students %}
                            <li><a class="dropdown-item"
                                   href="{% url 'list-of-students' %}">List of
                                students</a></li>
                            {% endif %}

                        </ul>
                    </li>
                {% endif %}
                    {#                <li class="nav-item dropdown">#}
                    {#                    <a class="nav-link dropdown-toggle" href="#" role="button"#}
                    {#                       data-bs-toggle="dropdown" aria-expanded="false">#}
                    {#                        Students#}
                    {#                    </a>#}
                    {#                    <ul class="dropdown-menu">#}
                    {#                        <li><a class="dropdown-item"#}
                    {#                               href="{% url 'create-student' %}">Create a new#}
                    {#                            student</a></li>#}
                    {#                        <li><a class="dropdown-item" href="#">Create a new#}
                    {#                            trainer</a></li>#}
                    {##}
                    {#                    </ul>#}
                    {#                </li>#}


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Trainers
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item"
                                   href="{% url 'create-trainer' %}">Create a
                                new
                                trainer</a></li>
                            <li><a class="dropdown-item"
                                   href="{% url 'list-trainers' %}">List of
                                trainers</a></li>

                        </ul>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Feedback
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item"
                                   href="{% url 'create-feedback' %}">Create a
                                new feedback</a></li>
                            <li><a class="dropdown-item" href="{% url 'list-of-feedbacks' %}">List of
                                feedbacks</a></li>

                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#"
                           role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            List of trainers
                        </a>
                        <ul class="dropdown-menu">
                            {% for trainer in trainers %}
                                <li>
                                    <a class="dropdown-item"
                                       href="#">{{ trainer }}</a>
                                </li>
                            {% endfor %}

                        </ul>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-light dropdown-toggle" type="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        My profile
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item"
                               href="{% url 'password_change' %}">Change
                            password</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout, {{ request.user.username }}</a>
                        </li>

                    </ul>
                </div>



                {#                </div>#}
                {##}
                {##}
                {#                <div>#}
                {#                    <a href="{% url 'logout' %}" class="btn btn-outline-danger">Logout, {{ user.username }}</a>#}
                {#                </div>#}

            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-success">Login</a>
                    <a href="{% url 'create-user' %}"
                       class="btn btn-outline-secondary">Sign up</a>
                </div>

            {% endif %}
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search"
                       placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search
                </button>
            </form>
        </div>
    </div>
</nav>